### ISSUE TITLE
OpenAL Installation

### ISSUE THREAD

**Issue by MjnMixael** [ngld/old-knossos#100]
Not sure who needs to handle this, FSO or Knossos, but we need to make sure OpenAL installation is taken care of.

**Comment by ngld** [comment]
Since OpenAL is just a DLL, we don't need to install it. We just need to make sure that FSO can find it. Knossos already bundles OpenAL Soft on Windows for the settings screen so I'd say we just make sure that FSO can find that and everything should be fine.

The only problem here is that Knossos currently only bundles the 32bit version. Adding the 64bit version isn't hard but I'm not sure how to make FSO load the correct DLL. With only one version, I'd just add the directory that contains the file at the end of the `PATH`. Maybe we can have two directories and add both to the `PATH`?
Either way, I'll figure it out.

An alternative solution would be to bundle OpenAL Soft with FSO releases just like they already bundle SDL and FFmpeg but I think the SCP coders don't want to.

**Comment by MjnMixael** [comment]
IMO, FSO should bundle it with the rest of the DLLs. Not sure why they don't already.

**Comment by ngld** [comment]
EDIT: The next nightlies will bundle OpenAL Soft.

**Comment by ngld** [comment]
A [PR to bundle OpenAL with FSO](https://github.com/scp-fs2open/fs2open.github.com/pull/1531) has been opened. I guess we can close this issue once that's been merged.
