### ISSUE TITLE
Minor issues with Linux desktop integration

### ISSUE THREAD

**Issue by asarium** [ngld/old-knossos#109]
I found two minor issues while trying to enable the desktop integration of my development checkout of Knossos:
1. The icon did not show up properly. I'm not sure if that is exclusive to my setup since the desktop file references the source location directly. The desktop file uses a relative path (`Icon=data/hlp.png`) which may explain why the icon does not show up correctly. This should be relatively easy to fix by using an absolute path but I am not sure how that would affect the installation of the system packages.
2. The custom protocol handle does not work for some reason. I'll have to debug this a bit further before I can provide some additional information on why this could be broken.

**Comment by ngld** [comment]
1. That's exactly the reason it didn't work for you. Changing the code shouldn't cause problems for the system packages since they have their own static `.desktop` files and don't use the code.
2. Take a look at your `~/.local/share/applications/mimeapps.list`, it probably uses the wrong case for `knossos.desktop`.

That latest commit should fix both issues. If you want to further debug the protocol handle issue, take a look at `xdg-mime`. `xdg-mime query default x-scheme-handler/fso` displays the associated program which in this case should be `knossos.desktop`.

**Comment by asarium** [comment]
Thank you for the fix. I can confirm that your commit fixed both issues for me. However, it seems like Firefox does not use `xdg-open` for handling custom protocols which means that it still doesn't recognize the `fso://` protocol. I'll dig around in their documentation a bit since there must be some way to convince Firefox to open that URL correctly.

**Comment by asarium** [comment]
I fixed the issue by following the [Mozilla page](http://kb.mozillazine.org/Register_protocol) about that topic. This probably was some kind of issue with the default configuration so it wasn't an issue with Knossos.
