### ISSUE TITLE
Uninstalling from a mod's detail page doesn't reset you to a sane state

### ISSUE THREAD

**Issue by chief1983** [ngld/old-knossos#110]
I viewed a mod's details from my Home page, and uninstalled it.  It left me on that page though, with the play button, etc still available.  It should probably update to the state of an uninstalled mod viewed from the Explore tab at that point (I'm not sure if there is actually a difference in states based on where you came from or not).

**Comment by ngld** [comment]
This is probably another state propagation issue. *sigh*
The state is updated but due to the way the UI currently works the new state doesn't arrive in the template (probably because the version selector in the detail page breaks the reference).

I'll have to look into this more but it's going to take a while.

**Comment by ngld** [comment]
Turns out this was caused by a broken reference but for a completely different reason: After uninstalling, the mod metadata was gone which caused errors during the UI update. The result was that the UI wasn't updated at all and just remained as it was.
To fix this, Knossos now exits the details tab in this case.
