### ISSUE TITLE
Implement an updater for macOS

### ISSUE THREAD

**Issue by ngld** [ngld/old-knossos#19]
Knossos should be able to update automatically on macOS (similar to what happens on Windows).

**Comment by chief1983** [comment]
I might as well mention it here too, the mechanism usually used by an app is to actually move itself to the trash while running and place the new, just downloaded, app in its former location.  This doesn't break the running app because the trash doesn't actually remove the file, change its descriptor, etc, so the app can keep running.  Then they usually trigger a close of themselves and a restart of the new app.  I don't know how to do any of those things, but that's the normal observed procedure.  Not sure how much of that applies here.

**Comment by ngld** [comment]
A simple updater has been implemented and seems to be working. If someone can figure out how to write a complete updater, I'd gladly accept a PR or implement it myself. Until then, I'm happy with the current updater.
