### ISSUE TITLE
Mods not being mirrored correctly lead to installation issues

### ISSUE THREAD

**Issue by Goober5000** [ngld/old-knossos#203]
This was discovered by woutersmits and can be seen with the FS1 COOP mod:
https://fsnebula.org/mod/fs1coopup

The "dummy missions" package has a broken link on cf.fsnebula.org, despite intact links on fsnebula.org and  porphyrion.feralhosting.com.  This broken link is enough to prevent this package from being downloaded.  Each time, the "error occurred" dialog box appears:
![Clipboard01](https://user-images.githubusercontent.com/1878523/86039785-ef953e80-ba10-11ea-9d80-96baa0b5eb99.jpg)

Even when I manually downloaded the "dummy missions" package and put them in the proper spot, then clicked Verify Files, Knossos said the package was not valid.

**Comment by ngld** [comment]
This has nothing to do with mirroring and everything with the long-standing issues in Knossos' upload logic.

The downloads work fine. If a download fails it's retried multiple times and at least 4 times against each mirror before Knossos gives up. As such a mirror being down or missing files couldn't cause this.

However, Knossos uploaded the wrong checksum list which causes the checksum validation to *always* fail. Knossos expects loose files although the archive contains a `.vp`. Here's the relevant log:
```
WARNING:Thread-3:tasks.work2: Missing file "./dummy.fs2" from archive "dummy_missions.7z" for package "dummy_missions" (FS1 COOP UP)!
ERROR:Thread-3:tasks.work2: Failed to unpack archive "dummy_missions.7z" for package "dummy_missions" (FS1 COOP UP)!          
```

To further demonstrate, here's an example of a failed download due to missing files on cf.fsnebula.org.
```
DEBUG:Thread-1:connectionpool._new_conn: Starting new HTTPS connection (4): cf.fsnebula.org:443
DEBUG:Thread-1:connectionpool._make_request: https://cf.fsnebula.org:443 "GET /storage/1c/83/22af72c3d70f1e42721dd807b26ca9218f340d44d7781daba573a14f7d79 HTTP/1.1" 404 None
ERROR:Thread-1:util.download: Failed to load "https://cf.fsnebula.org/storage/1c/83/22af72c3d70f1e42721dd807b26ca9218f340d44d7781daba573a14f7d79"! (404 Not Found)
ERROR:Thread-1:tasks.work2: Download of "https://cf.fsnebula.org/storage/1c/83/22af72c3d70f1e42721dd807b26ca9218f340d44d7781daba573a14f7d79" failed!
INFO:Thread-1:util.download: Downloading "https://porphyrion.feralhosting.com/datacorder/nebula/1c/83/22af72c3d70f1e42721dd807b26ca9218f340d44d7781daba573a14f7d79"...
DEBUG:Thread-1:connectionpool._new_conn: Starting new HTTPS connection (2): porphyrion.feralhosting.com:443
DEBUG:Thread-1:connectionpool._make_request: https://porphyrion.feralhosting.com:443 "GET /datacorder/nebula/1c/83/22af72c3d70f1e42721dd807b26ca9218f340d44d7781daba573a14f7d79 HTTP/1.1" 206 80273
```

**Comment by ngld** [comment]
I've fixed the checksum issue. Once you refresh your mod list and reinstall the mod, everything should work as expected.

**Comment by Goober5000** [comment]
Thanks!
