### ISSUE TITLE
FSO crashes during launch

### ISSUE THREAD

**Issue by ngld** [ngld/old-knossos#4]
The used cmdline_fso.cfg:

```
-mod mediavps_3612 -missile_lighting -3dshockwave -post_process -fxaa -dualscanlines -orbradar -rearm_timer -ship_choice_3d -weapon_choice_3d -3dwarp -warp_flash -snd_preload -fb_explosions -keyboard_layout "azerty" -ambient_factor 75 -spec_exp 11 -spec_point 0.6 -spec_static 0.8 -spec_tube 0.4 -ogl_spec 60
```

The actual error message: 

```
Starting FS2 Open (/home/loris/FreeSpace 2 beta/fs2_open_3.7.1_llvm_BP) failed! (return code: -11)
```

Check wxLauncher (and possibly others) to see if I missed anything. This should be resolved by fixing `run_fs2` once I find out why FSO crashes.

**Comment by Hellzed** [comment]
Sorry for that, the bug was not on this side : my computer is a nvidia optimus laptop, and currently fs2_open segfaults on the Intel driver. If I run ./manager.py on the nvidia driver, the game does too, and everything runs fine.

That's good to know. I will check if I can add something to detect this kind of hardware (usually lspci grep | VGA or lspci grep | 3D , and then add the command "primusrun" before "python" in the launcher) and make sure the game runs on the right graphics device.

**Comment by ngld** [comment]
Thanks, that's good to know!
On some platforms you need to use "optirun" instead of "primusrun" so you might want to check which of those commands is available.
