### ISSUE TITLE
Some things I noticed

### ISSUE THREAD

**Issue by Goober5000** [ngld/old-knossos#55]
1) "You need to select a directoy where Knossos will store the game data (models, textures, etc.)." -- first, "directory" is misspelled; second, a sensible default should be provided.  Maybe %APPDATA%\knossos.  I used My Documents\knossos for the time being.

2) The installation program said it would create an icon on my desktop.  It created an icon for the administrator user, but it didn't create an icon for my standard user.  (When I launched it, it displayed the UAC dialog.)  Neither did it create a start menu icon or group for my standard user.

3) If there are no mods currently found, I suggest starting on the "Explore" tab instead of the "Home" tab.

4) I was browsing through the Settings tab, when a mod download completed and it yanked me back to the Explore tab.  Suggest not overriding the tab like that.

**Comment by ngld** [comment]
1) @MjnMixael [proposed a better introduction](http://www.hard-light.net/forums/index.php?topic=94068.msg1857138#msg1857138) which should address that issue
2) Haven't noticed that yet but I'll look into it. I guess the installer didn't handle the paths properly (used the admin's folders since it was running as admin).
3) A good idea!
4) Did that only happen with the Settings tab? If that's the case, it should be an easy fix.

**Comment by Goober5000** [comment]
The Settings tab is the only one I've noticed it on so far, though I should test it with some more mods.

**Comment by Goober5000** [comment]
Regarding #4, this isn't limited to the Settings page.  If Knossos happens to refresh the mod list when you are editing campaign metadata, it will clear all unsaved metadata (e.g. campaign description) and you'll have to type it all in again.

**Comment by ngld** [comment]
All of these should be fixed now. I'll close the issue after the next beta is released.
