### ISSUE TITLE
Duplicate Mod Issues

### ISSUE THREAD

**Issue by MjnMixael** [ngld/old-knossos#56]
So, say I create a mod called "test" locally and there's also a mod "test" on Nebula. I mean.. who would be so lazy as to name a mod "test" anyway?! But say they also happen to have the same lazy mod ID. (What a coincidence!) Knossos will check the local mod against the Nebula version, even if the local one was just created.

My Test mod was 1.0.0. The Nebula version is 2.1.1. Amazing! My brand new mod already has an update available!

Additionally, now I can't delete my local mod, because I don't have permission to delete the Nebula version of "Test".

I realize this may be a niche case, but something we should think about. I'm thinking a system should be implemented where knossos either askes Nebula if there's duplicates before creating a mod locally OR chooses the ModID automatically, forcing it to just be randomly numerical or hex or something.

**Comment by ngld** [comment]
The mod ID is used to generate a folder name during installation. Checking for a duplicate name during mod creation seems like the best solution to me.

Using randomly generated IDs would avoid this in the first place but I **really** like seeing messages like
```
Starting mod "Derelict" with cmdline " -mod Derelict-1.0.0\content,MVPS-3.6.12\mv_root,MVPS-3.6.12\mv_assets,MVPS-3.6.12\mv_effects,MVPS-3.6.12\mv_music,MVPS-3.6.12\mv_advanced,MVPS-3.6.12\mv_animglows,MVPS-3.6.12\mv_radaricons,MVPS-3.6.12\mv_cb_ani_1,MVPS-3.6.12\mv_cb_ani_2" and tool "...\bin\FSO-3.8.1-20171031\windows/x64/fs2_open_3_8_1_20171031_e2d8502_x64_SSE2.exe".
```
instead of
```
Starting mod "as324dfae2342123" with cmdline " -mod as324dfae2342123-1.0.0\content,ads78234jkln-3.6.12\mv_root,ads78234jkln-3.6.12\mv_assets,ads78234jkln-3.6.12\mv_effects,ads78234jkln-3.6.12\mv_music,ads78234jkln-3.6.12\mv_advanced,ads78234jkln-3.6.12\mv_animglows,ads78234jkln-3.6.12\mv_radaricons,ads78234jkln-3.6.12\mv_cb_ani_1,ads78234jkln-3.6.12\mv_cb_ani_2" and tool "...\bin\FSO-3.8.1-20171031\windows/x64/fs2_open_3_8_1_20171031_e2d8502_x64_SSE2.exe".
```

**Comment by MjnMixael** [comment]
Sounds good to me. Do we need to worry about offline situations much? I'm thinking the user is not connected online and creates a mod. I mean, the chances of someone creating a mod with the same modid as someone else (usually the mod name again) is pretty slim in the first place outside of "test".

**Comment by ngld** [comment]
I think we can just display a warning if the user is offline that the mod ID can't be checked and they're proceeding at their own risk. The warning should allow them to Retry (in case the request failed for some weird reason and they actually are online), Cancel or Continue

The warning could be something like `Knossos couldn't check if your mod ID is unique because it couldn't connect to the Nebula. Continue at your own risk if you're sure it is unique, otherwise please abort.`.
If the request succeeds and the mod ID is already used, the message would be `Your chosen mod ID is already being used by someone else. Please choose a different one.`.

**Comment by MjnMixael** [comment]
I think that will work perfectly.
